### ISSUE TITLE
No chart is displayed

### ISSUE THREAD

**Issue by codesbyhusnain** [justinkx/react-crypto-chart#4]
I have installed the package and am using the widget but there is nothing visible. How to troubleshoot this issue?

**Comment by justinkx** [comment]
> I have installed the package and am using the widget but there is nothing visible. How to troubleshoot this issue? 

Can you share the exact code used ? Is there any error thrown in the console?

You can checkout this example app for more details https://github.com/justinkx/crypto-connect-web

**Comment by codesbyhusnain** [comment]
I installed the package using Yarn
Then I imported it using: `import TradeViewChart from "react-crypto-chart"`
And then I am using it inside my React component: 
`<TradeViewChart pair="BTCUSD" />`
But there is nothing being displayed on my UI. No image or widget

**Comment by codesbyhusnain** [comment]
I see in the example, you are using dynamic import. I am using it in a plain React app, not Next. Any way to make it work in a React app?

**Comment by justinkx** [comment]
> I installed the package using Yarn Then I imported it using: `import TradeViewChart from "react-crypto-chart"` And then I am using it inside my React component: `<TradeViewChart pair="BTCUSD" />` But there is nothing being displayed on my UI. No image or widget


**BTCUSD** is not a valid binance pair. It should be **BTCBUSD** or **BTCUSDT**.
Use this API to fetch the tickers and make use of the valid symbols: https://api.binance.com/api/v3/ticker/24hr

**Comment by codesbyhusnain** [comment]
Putting BTCUSDT doesn't give any result either.

**Comment by justinkx** [comment]
> Putting BTCUSDT doesn't give any result either.

I verified locally and It's working. You can check the example app by passing different pairs and it's giving valid graph
https://crypto-connect-web.vercel.app/?pair=ETHUSDT
https://crypto-connect-web.vercel.app/?pair=BTCBUSD
https://crypto-connect-web.vercel.app/?pair=BTCUSDT

And check the code in example app, pair passed in the url route is used in the <TradeViewChart /> component
https://github.com/justinkx/crypto-connect-web/blob/main/pages/index.js

**Comment by codesbyhusnain** [comment]
Once again, the example code is using next whereas I am using plain React. Can you please confirm if it works for just React?

**Comment by justinkx** [comment]
> Once again, the example code is using next whereas I am using plain React. Can you please confirm if it works for just React?

Sorry for late reply, The chart container require styling which was using a className container. It conflict with other component classes, so I've modified the library with a new **containerStyle** prop with min required default values. Please update to latest version of the package , v0.0.5 and try. I have added an example app and updated README.md
