### ISSUE TITLE
Return screenshot instead of graph

### ISSUE THREAD

**Issue by codesbyhusnain** [justinkx/react-crypto-chart#6]

**Comment by codesbyhusnain** [comment]
How do I edit the height of the widget from layout? Width is editable but not height

**Comment by codesbyhusnain** [comment]
Giving any props to the widget breaks it. The only way it works if you give it specific hardcoded symbol

**Comment by justinkx** [comment]
Sorry for the late reply. Haven't got time to look into the issue. I have updated the issues and publish the changes. Please checkout to latest version.
Example for your reference: https://stackblitz.com/edit/react-crypto-chart?file=src%2FApp.js

**Comment by codesbyhusnain** [comment]
Works fine on online code IDEs but breaks when use in a react project

**Comment by codesbyhusnain** [comment]
One graph breaks into multiple graphs and so on

**Comment by justinkx** [comment]
> One graph breaks into multiple graphs and so on

Didn't understand what that exactly mean? Please check the example project which is a react project. StackBlitz is just an online replica, nothing different

**Comment by codesbyhusnain** [comment]
Is there a possibility that the widget would return an image instead of the whole graph? 
A screenshot of sorts.

**Comment by justinkx** [comment]
> Is there a possibility that the widget would return an image instead of the whole graph? 
> A screenshot of sorts. 
> 

Currently this doesnot provide that feature. You can fork and try on it.
