### ISSUE TITLE
Documentation mismatch

### ISSUE THREAD

**Issue by rafaelfaria** [justinkx/react-crypto-chart#8]
Your documentation says the props are not required however Typescript says otherwise :) 
<img width="1319" alt="image" src="https://user-images.githubusercontent.com/227917/170993497-d11fc889-92cb-4828-906b-befb31a8c5af.png">

you should use `?` on each one of them if you want to make them optional.

```

export interface Props {
    pair: string;
    interval?: string;
    candleStickConfig?: CandleStickConfig;
    histogramConfig?: HistogramConfig;
    chartLayout?: DeffaultChartLayout;
    containerStyle?: {
        [x: string]: any;
    };
}
```

**Comment by justinkx** [comment]
Have mainly used it in my personal projects which are not in typescript so haven't faced this. I've added default values to each props just in case it's not supplied. Happy to merge the change if you could provide a PR
